name: Build and push Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*"

env:
  RENV_PATHS_ROOT: ~/.cache/R/renv

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Setup renv and  cache
        id: cache-renv
        uses: r-lib/actions/setup-renv@v2
        with:
          profile: '"shiny"'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/firms-gta/tunaatlas_pie_map_shiny_CWP_database
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.url=${{ github.repository }}
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.title=GlobalTunaAtlasExplorer
            org.opencontainers.image.description=Interactive Shiny application for Tuna Atlas data visualization
            org.opencontainers.image.vendor=IRD
            org.opencontainers.image.author=Julien Barde <julien.barde@ird.fr>

      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
